MMPOSE Support
nyunAI/nyuntam_adapt pull request #10
Opened 2024-07-30 13:35 UTC by Abhrant

This PR adds support for MMPOSE

2024-08-01 09:50 UTC, shwu-nyunai requested changes

2024-08-01 09:50 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +        args = kwargs["MMLABS_ARGS"]
can we use the adaptparam.mmlabsargs for task initialisation and subsequent access to args?

2024-08-01 09:50 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +            )
if these workdirs are used by mm libs for model downloading and config downloading; can we move these to suitable paths inferred from jobpaths/outputpaths/cachepaths ?

2024-08-01 09:50 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
the structure for all the tasks looks similar and redundant. lets have a common class with common methods such as adapt, download checkpoints, check_config, get_checkpointing_modules, etc and extend all mmtasks from it to avoid redundancy;

2024-08-01 09:50 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +                pass
similar issue as in mmseg pr.

2024-08-01 09:54 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
The reason why I don't have a common parent class is that all these tasks are supposed to be independent of each other. Each task is suposed to be a module of it's own and can have any structure. Adding a different parent classs for only mm tasks doesn't make sense as there will be multiple such frameworks and tasks in the future. Why have one parent class for only 3 of such tasks?

2024-08-01 09:58 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
we dont necessarily need a parent class, these tasks can extend/overwrite from each other as sibling classes as well. just reuse the methods from an already implemented class to avoid redundancy. specially when there is little or no change at all in the methods.

2024-08-02 09:31 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
This is not being done. These tasks are supposed to be completely independent of each other and so, they are designed to work even if any one of them isn't there. So, there is no point to doing this.

2024-08-05 07:17 UTC, Arnav0400 commented on tasks/pose_estimation_mmpose/task.py
> +        args = kwargs["MMLABS_ARGS"]
@Abhrant

2024-08-05 07:17 UTC, Arnav0400 commented on tasks/pose_estimation_mmpose/task.py
> +            )
@Abhrant

2024-08-05 07:36 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +        args = kwargs["MMLABS_ARGS"]
@shwu-nyunai , Same issue as in MMDET. Please resolve

2024-08-05 08:35 UTC, shwu-nyunai requested changes

2024-08-05 08:35 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +        args = kwargs["MMLABS_ARGS"]
not in current scope of efforts. resolve.

2024-08-05 08:35 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +            work_path = osp.join(ROOT, "user_data/jobs/Adapt/mmpose_cache")
why are we hardcoding the cache path? afaik we get a cache path in the yaml, right? why can't we use that for caching? 
if we don't get a cache path in the yaml, we can use - output dir "/cache"?

also, the user_data dir is not fixed, it may vary based on what the user sets it in the yaml; how do we plan to account for that?

@Arnav0400 what's your opinion?

2024-08-05 08:38 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +            work_path = osp.join(ROOT, "user_data/jobs/Adapt/mmpose_cache")
Yeah. I am fixing this.

2024-08-05 09:42 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +            work_path = osp.join(ROOT, "user_data/jobs/Adapt/mmpose_cache")
@shwu-nyunai

2024-08-05 09:46 UTC, shwu-nyunai requested changes

2024-08-05 09:46 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +                ROOT , self.output_dir, "cache" , osp.splitext(osp.basename(config_file))[0]
are we sure that the output_dir will always be a sub-dir of the root? 
afaik, for cli, the output dir is absolute; for local runtimes it could be anything; we can simply base it off of the output_dir

2024-08-05 09:52 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +                ROOT , self.output_dir, "cache" , osp.splitext(osp.basename(config_file))[0]
makes sense. Updating.

2024-08-05 09:53 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +                ROOT , self.output_dir, "cache" , osp.splitext(osp.basename(config_file))[0]
@shwu-nyunai

2024-08-05 09:53 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +            )
@shwu-nyunai , should I resolve this?

2024-08-05 09:53 UTC, Abhrant commented on tasks/pose_estimation_mmpose/task.py
> +                pass
@shwu-nyunai this can be resolved now ?

2024-08-05 10:01 UTC, shwu-nyunai approved these changes
lgtm. 👍🏻

2024-08-05 11:24 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +                pass
I believe we should add a break statement once we update the paths. ideally we should not see multiple .pt/.pth files. pt3 was to catch such multiple .pt/.pth occurrences and choose (or) restrict only to one

2024-08-05 14:08 UTC, Arnav0400 commented
> lgtm. 👍🏻

There is a minor merge conflict @Abhrant @shwu-nyunai

2024-08-05 15:40 UTC, merged