MM Vision
nyunAI/nyuntam_adapt pull request #13
Opened 2024-08-06 06:02 UTC by Abhrant

This PR adds all the approved changes form PR #8 #9 #10 #12  into main.

2024-08-06 07:12 UTC, shwu-nyunai requested changes

2024-08-06 07:12 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +                    self.logger.info(f"MODEL WEIGHTS WILL BE LOADED FROM {file}")
Let's not use uppercasing here. same for any/all other such occurrences.

2024-08-06 07:12 UTC, shwu-nyunai commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
redundant import; lets run it all through black formatter if not already.

2024-08-06 07:43 UTC, Abhrant commented on core/custom_model.py
> +                print("Found a full model file.")
The pint statements report to the logger.

2024-08-06 07:49 UTC, shwu-nyunai commented on core/custom_model.py
> +                print("Found a full model file.")
then we can replace it with logger

2024-08-08 11:27 UTC, Abhrant commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
Done.

2024-08-11 16:18 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                    self.logger.info(f"MODEL WEIGHTS WILL BE LOADED FROM {file}")
Done

2024-08-12 05:10 UTC, shwu-nyunai requested changes

2024-08-12 05:10 UTC, shwu-nyunai commented on core/custom_model.py
> +                print("Found a full model file.")
awaiting changes on this. @Abhrant

2024-08-12 05:10 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +        # config_key = MMdetection_Default_Model_mapping[model_name]
lets remove this commented out line if not needed.

2024-08-12 05:10 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +        # runner.cfg.activation_checkpointing = self.get_checkpointing_modules(self.model)
can be removed.

2024-08-12 05:10 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +        # self.cfg.train_dataloader.dataset.metainfo = self.cfg.metainfo
can be removed

2024-08-12 05:10 UTC, shwu-nyunai commented on tasks/pose_estimation_mmpose/task.py
> +        # self.cfg.val_dataloader.dataset.metainfo = self.cfg.metainfo
can be removed

2024-08-12 06:20 UTC, Abhrant commented on core/custom_model.py
> +                print("Found a full model file.")
One of the reasons for adding the stdout in the logger was to ensure that print statements can also be written to the logger. This makes things pretty easy. So, can we keep this ?

2024-08-12 06:20 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                    self.logger.info(f"MODEL WEIGHTS WILL BE LOADED FROM {file}")
Resolve this @shwu-nyunai

2024-08-12 06:20 UTC, Abhrant commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
resolve this @shwu-nyunai

2024-08-12 06:29 UTC, shwu-nyunai commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
I still have no access to the repository. kindly resolve if fixed.

2024-08-12 08:31 UTC, shwu-nyunai commented on tasks/summarization_hf/task.py
why is the name of this class Seq2Seq if we have a class `Translation` for the other seq2seq task. Is this supposed to be extended to Translation?

2024-08-12 10:35 UTC, Abhrant commented on core/custom_model.py
> +                print("Found a full model file.")
@shwu-nyunai

2024-08-12 10:37 UTC, Abhrant commented on tasks/summarization_hf/task.py
This was an oversight from the very beginning of ADAPT. Since multiple people worked on this, I think this got mized up. Changing this now will not be ideal. So, let's keep it like this for now.

2024-08-13 04:52 UTC, shwu-nyunai approved these changes

2024-08-13 05:06 UTC, merged