integration changes
nyunAI/nyuntam_adapt pull request #14
Opened 2024-08-13 08:07 UTC by shwu-nyunai

- adds the changes required for nyuntam <-> adapt integrations

2024-08-13 20:06 UTC, Abhrant commented
@shwu-nyunai 

On runnning it, I get this error : 


08/14/2024 03-04-23 - ERROR - nyuntam.factory - [[<class 'nyuntam_adapt.factory.AdaptFactory'>]] 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/workspace/nyuntam/factory.py", line 110, in create_from_dict
    instance = caller(args)
  File "/workspace/nyuntam/nyuntam_adapt/factory.py", line 29, in __init__
    super().__init__(kwargs)
  File "/workspace/nyuntam/factory.py", line 77, in __init__
    self.__pre_init__(args)
  File "/workspace/nyuntam/nyuntam_adapt/factory.py", line 26, in __pre_init__
    super().__pre_init__(kwargs)
  File "/workspace/nyuntam/factory.py", line 83, in __pre_init__
    job_service = JobServices.get_service(
  File "/workspace/nyuntam/constants/keys.py", line 12, in get_service
    if service.lower() == "adapt":
AttributeError: 'NoneType' object has no attribute 'lower'
08/14/2024 03-04-23 - ERROR - root - Failed to create Factory instance: Factory instance could not be created.
Traceback (most recent call last):
  File "/workspace/nyuntam/main.py", line 18, in main
    factory = Factory.create_from_yaml(args.yaml_path)
  File "/workspace/nyuntam/factory.py", line 146, in create_from_yaml
    return cls.create_from_dict(args)
  File "/workspace/nyuntam/factory.py", line 115, in create_from_dict
    raise Exception("Factory instance could not be created.")
Exception: Factory instance could not be created.
08/14/2024 03-04-23 - CRITICAL - root - Critical failure in main execution: Factory instance could not be created.

2024-08-14 04:25 UTC, Abhrant requested changes

2024-08-14 08:36 UTC, shwu-nyunai commented on factory.py
> +        super().__pre_init__(kwargs)
should be *args, **kwargs instead. fixed in the revision.

2024-08-14 08:38 UTC, shwu-nyunai commented on factory.py
fixed with [AdaptionAlgorithm fix](https://github.com/nyunAI/nyuntam/pull/6/commits/68152db10b731d1f17f74acf62f79ce2dbd69993)

2024-08-20 09:50 UTC, Abhrant approved these changes

2024-08-20 09:50 UTC, Abhrant commented
@Arnav0400 , we can merge this one too

2024-08-20 10:28 UTC, merged