MMDET support
nyunAI/nyuntam_adapt pull request #8
Opened 2024-07-30 13:28 UTC by Abhrant

This PR adds mmdet support

2024-08-01 08:02 UTC, shwu-nyunai requested changes

2024-08-01 08:02 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +                pass
to the best of my understanding, this code block is only expected to update the cfg with the details of where to load the weights from; and is wrapped inside an exception handler which is supressing any exceptions raised. 

1. what are the consequences of failing to set the accurate path to the weights to load from?
2. if we are confident that the updates to config would never fail, do we still need to handle exceptions?
3. also, how do we decide which file to choose if multiple .pth/.pt files exist?
    - as per the [docs](https://docs.python.org/3/library/pathlib.html#pathlib.Path.iterdir) "The children are yielded in arbitrary order"

2024-08-01 08:28 UTC, shwu-nyunai commented
also, we are only adding the configs of the models we support and related configs right?

2024-08-01 08:31 UTC, shwu-nyunai requested changes

2024-08-01 08:31 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +        args = kwargs["MMLABS_ARGS"]
since we have a well defined data classes for adaptparams and mmlabargs, why not use them?

https://github.com/nyunAI/nyuntam_adapt/blob/3310038830a9b34c765fcd71db3d45f1a7d35581/utils/params_utils.py#L156

2024-08-01 08:47 UTC, Abhrant commented on core/base_algorithm.py
> +                    "bbox head of model is not DETRHead"
done

2024-08-01 08:47 UTC, Abhrant commented on core/base_algorithm.py
> +                or isinstance(detection_head_obj, RTMDetSepBNHead)
done.

2024-08-01 08:50 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                        self.logger.info(f"MODEL WEIGHTS LOADED FROM {file}")
changed to "will be"

2024-08-01 09:23 UTC, shwu-nyunai commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
what are these paths? if not permanent, are these cleaned after the job is completed?

2024-08-01 09:25 UTC, Abhrant commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
These paths are updates from the user's yaml file.

2024-08-01 09:30 UTC, shwu-nyunai commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
I meant, what are these used for? and should these be relative? if yes, relative to what path?

2024-08-01 09:40 UTC, Abhrant commented on tasks/custom_model.py
>          raise CustomModelLoadError(f"Following Error Happened : {e}") from e
Moreover the Exception 'e' is supposed to return the full tsack trace of the error which will be elaborate.

2024-08-01 09:42 UTC, Abhrant commented on tasks/custom_model.py
> +        raise CustomModelLoadError(f"Following Error Happened : {e}") from e
Again, the 'e' is supposed to give the stack trace

2024-08-01 10:08 UTC, Abhrant commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
These are placeholder values. These need to updated by the user when they give the path of the respective files. These aren't relative, currently they are just placeholder values.

2024-08-01 11:02 UTC, shwu-nyunai commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
if these are just placeholders, can these also be empty?

2024-08-01 17:33 UTC, Abhrant commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
These can also be empty. There are just set according to the naming conventions of coco annotation files.

2024-08-01 18:08 UTC, shwu-nyunai commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
even if set according to naming conventions, these tend be the default values that will go down to the subsequent tasks. lets default them to defaults in the yaml (ideally one best working recipe)

2024-08-01 19:06 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +        args = kwargs["MMLABS_ARGS"]
@shwu-nyunai Agreed, this was a oversight that happened from the very beginning.  Changing this now will require changes to all the task modules and using it as kwargs works for now so I guess we can move ahead with this.

2024-08-01 19:11 UTC, Abhrant commented on core/base_algorithm.py
> +                    self.logger.info(f"Unfreezed {name}")
@shwu-nyunai  since the logger is currently set as a class attribute which is accesibale from any method in the class, it serves the same purpose as a global varibale. Please explain why it would be necessary to set logger as a global variable and elevate it out of class. We are already accessing a common logger with just the _name_ attribute set.

2024-08-01 20:05 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                pass
did this.

2024-08-02 06:43 UTC, Abhrant commented on .gitmodules
done.

2024-08-02 10:44 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +        args = kwargs["MMLABS_ARGS"]
okay

2024-08-02 11:29 UTC, shwu-nyunai requested changes

2024-08-02 11:29 UTC, shwu-nyunai commented on core/base_algorithm.py
> +                    self.logger.info(f"Unfreezed {name}")
resolve

2024-08-02 11:29 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
awaiting a comment on this. if fixed, resolve this.

2024-08-02 11:29 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +        args = kwargs["MMLABS_ARGS"]
resolve

2024-08-02 11:29 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +        self.logger = logging.getLogger(__name__)
ignore. resolved

2024-08-02 11:29 UTC, shwu-nyunai commented on tasks/translation_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
combine imports

2024-08-02 11:29 UTC, shwu-nyunai commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
imports from same module can be combined

2024-08-02 11:31 UTC, Abhrant commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
These are all done in refactor/modules PR that was merged.

2024-08-02 11:32 UTC, Abhrant commented on tasks/translation_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
These are all done in refactor/modules PR that was merged.

2024-08-02 11:33 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
resolved

2024-08-02 11:33 UTC, Abhrant commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
resolve this @shwu-nyunai ?

2024-08-02 12:12 UTC, shwu-nyunai commented on tasks/translation_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
okay. resolve please.

2024-08-02 12:12 UTC, shwu-nyunai commented on tasks/summarization_hf/task.py
> +from nyuntam_adapt.utils.task_utils import ModelLoadingError
sure. resolve please.

2024-08-02 12:13 UTC, shwu-nyunai commented on utils/params_utils.py
> +    work_dir: str = " ./results/mmdet"
idk where to check these fixes, hard to find the changes but this is minor. resolve.

2024-08-02 15:34 UTC, Abhrant commented on tasks/custom_model.py
> +        raise CustomModelLoadError(f"Following Error Happened : {e}") from e
@shwu-nyunai

2024-08-02 15:35 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                pass
@shwu-nyunai

2024-08-05 04:13 UTC, shwu-nyunai commented on tasks/custom_model.py
> +        raise CustomModelLoadError(f"Following Error Happened : {e}") from e
resolve.

2024-08-05 04:13 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +                pass
resolve.

2024-08-05 07:15 UTC, Arnav0400 requested changes

2024-08-05 07:15 UTC, Arnav0400 commented on tasks/custom_model.py
> +                return model
@Abhrant is this resolved?

2024-08-05 07:35 UTC, Abhrant commented on tasks/custom_model.py
> +                return model
@Arnav0400 @shwu-nyunai resolved

2024-08-05 08:13 UTC, shwu-nyunai commented on tasks/object_detection_mmdet/task.py
> +                pass
@Abhrant  can u explain what did we do to fix this? we only raised an exception? 
how does it fix pt.3 ?

2024-08-05 11:21 UTC, shwu-nyunai requested changes

2024-08-05 11:23 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                "nyuntam_adapt/tasks/object_detection_mmdet/mmdetection", config_file
Oh missed this. Fixing

2024-08-05 11:27 UTC, Abhrant commented on tasks/object_detection_mmdet/task.py
> +                "nyuntam_adapt/tasks/object_detection_mmdet/mmdetection", config_file
Done @shwu-nyunai

2024-08-05 11:36 UTC, merged