MMSEG
nyunAI/nyuntam_adapt pull request #9
Opened 2024-07-30 13:33 UTC by Abhrant

This PR adds support for MMSEG

2024-08-01 09:32 UTC, shwu-nyunai requested changes

2024-08-01 09:32 UTC, shwu-nyunai commented on tasks/image_segmentation_mmseg/task.py
> +                )
This should be a keyerror or attributeerror based on the type of self.cfg

2024-08-01 09:32 UTC, shwu-nyunai commented on tasks/image_segmentation_mmseg/task.py
> +                "nyuntam_adapt/tasks/image_segmentation_mmseg/mmsegmentation",
lets have at least one path derived at runtime and then create these paths using the derived path as reference.
ideally, we derive the ROOT of the package/submodule and create the paths in reference from that root.

example:

https://github.com/nyunAI/nyuntam/blob/5328f36b2658b3a93220938d17bbca68627009da/settings.py#L5

2024-08-02 07:57 UTC, Abhrant commented on tasks/image_segmentation_mmseg/task.py
> +                )
converted this to Attributer Error

2024-08-02 09:01 UTC, Abhrant commented on tasks/image_segmentation_mmseg/task.py
> +        args = kwargs["MMLABS_ARGS"]
This was an oversight from my end. Changin this will require a lot of changes in the internal structure. Let's continue with this as it it is.

2024-08-02 11:23 UTC, shwu-nyunai commented on tasks/image_segmentation_mmseg/task.py
> +                )
seems to be resolved. thanks.

2024-08-02 11:24 UTC, shwu-nyunai commented on tasks/image_segmentation_mmseg/task.py
> +        args = kwargs["MMLABS_ARGS"]
okay. resolved

2024-08-05 07:35 UTC, Abhrant commented on tasks/image_segmentation_mmseg/task.py
> +                "nyuntam_adapt/tasks/image_segmentation_mmseg/mmsegmentation",
@Arnav0400 , @shwu-nyunai  Please check

2024-08-05 08:24 UTC, shwu-nyunai approved these changes
awsm. 👍🏻

2024-08-05 11:35 UTC, shwu-nyunai approved these changes

2024-08-05 11:38 UTC, merged